version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - redis
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:denobili@db/scraping_db"
      REDIS_URL: "redis://redis:6379/0"

  worker:
    build: .
    command: celery -A celery_worker.celery_app worker --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:denobili@db/scraping_db"
      REDIS_URL: "redis://redis:6379/0"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: denobili
      POSTGRES_DB: scraping_db
    ports:
      - "5432:5432"
