"""Add error column to ScrapedData

Revision ID: 954330e5d9ed
Revises: d03a71884ea8
Create Date: 2025-02-15 14:44:22.302121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '954330e5d9ed'
down_revision: Union[str, None] = 'd03a71884ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
