"""Add error column to ScrapedData

Revision ID: d03a71884ea8
Revises: 
Create Date: 2025-02-15 14:27:24.954577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd03a71884ea8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraped_data', sa.Column('error', sa.String(), nullable=True))
    op.alter_column('scraped_data', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('scraped_data_url_key', 'scraped_data', type_='unique')
    op.create_index(op.f('ix_scraped_data_url'), 'scraped_data', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraped_data_url'), table_name='scraped_data')
    op.create_unique_constraint('scraped_data_url_key', 'scraped_data', ['url'])
    op.alter_column('scraped_data', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('scraped_data', 'error')
    # ### end Alembic commands ###
